name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c57367f248d14507c534db86ad784c3e356fedd13aa33f30bf5fb9e95897ec41"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
