name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae1584465ff3d765853883aa81b415ce611a70594f6de12b3487a5715e4094cc"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
