name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b57b13afdf866202dfdac0a8522625db5db304578ed058b452988c7ea8680867"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
