name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12c75e91eec9e11d79daec50b7c701ece7c5c7f77bae2f333eb383735e4d9ae8"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
