name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf7ae72aecfc2021fe0236ee5e0b18230be16a93142297a9ff741ea84c0baf37"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
