name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e30a315f8c57b795b77546b363e85f6a742f78fadd9181250156388e06288c3a"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
