name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "524d09f11a6110f2faedd89c65b2254d891ad4445febfdf1904589709e96d20b"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
