name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dee3f107ae352cfe560fd2a81091b0f3a131abe162332573cd5c361c20a1cb9"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
