name = "modern minecraft waow"
author = "dot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d42694bed89c017c393487c3ba75d61914036da0463c9f87db7ef243d45b9a48"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
